eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    # 发送心跳的间隔
    lease-renewal-interval-in-seconds: 30
    # 超过此时间若Eureka没收到心跳则认为该服务已挂
    lease-expiration-duration-in-seconds: 90
    # 写死自己的ip地址
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 80

spring:
  application:
    name: user-consumer

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500