eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka,http://127.0.0.1:10086/eureka
    # 拉取服务列表的时间间隔
    registry-fetch-interval-seconds: 10
  instance:
    # 写死自己的ip地址
    prefer-ip-address: true
    ip-address: 127.0.0.1
  user-provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.kingsley.consumer.loadbalancer.MyLoadBalanceRule

server:
  port: 80

spring:
  application:
    name: user-consumer

# 设置全局超时时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600